### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by euven** [matt-richardson/gocd-websocket-notifier#1]
Hi Matt,

I installed your plugin as per your configuration instructions on go-server 15.2, but I'm seeing the following exception in my logs:

<pre>
2015-11-27 10:22:38,000  WARN [63@MessageListener for PluginNotificationListener] PluginNotificationService:78 - Notification update failed for plugin: gocd.websocket.notifier
java.lang.RuntimeException: Interaction with plugin with id 'gocd.websocket.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [Unsuccessful response from plugin. 
Plugin returned with code '500' and the following response: '{"status":"failure","messages":[null]}']
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:38)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:74)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '{"status":"failure","messages":[null]}'
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:36)
        ... 8 more
</pre>

Could you have a look?

Thanks!
Eugene.

**Comment by matt-richardson** [comment]
Hi @eugeneventer. I've just released [0.4.0](https://github.com/matt-richardson/gocd-websocket-notifier/releases/tag/0.4.0), based on @uprial's change in #2. I believe it was the same issue - let me know how it goes!

**Comment by euven** [comment]
Hi Matt,

Thanks for looking into this one ;)

I replaced the 0.3 version with 0.4, restarted go-server, but now I cannot even connect to the websocket port. Unfortunately, I cannot see anything in the logs this time... Would you be able to investigate?

Cheers,
Eugene.

**Comment by matt-richardson** [comment]
Hi Eugene

Apologies for that – I tried to do it in a hurry, and its come back and bitten me.

So, I’ve recompiled the jar on ubuntu this time (rather than OS X) and re-uploaded version 0.4. (Probably should’ve upped the version, oh well.)

I gave it a test locally, using http://jsfiddle.net/EAVvQ/24/ pointing at ws://localhost:8887 and it seems happy.

Hopefully this all works for you this time!

Let me know if you do anything cool with it – would be nice to know that people are getting value out of it!

Cheers,
matt

**Comment by euven** [comment]
Thanks for the help Matt - it works now :)

I'm writing a jabber bot that listens for messages from your plugin, then posts to a room. I know I should probably write a GoCD plugin too, but I'm not a Java dev either, so it was just easier to use your plugin ;)

**Comment by euven** [comment]
https://github.com/eugeneventer/gobot <- my bot that uses your plugin :)

**Comment by matt-richardson** [comment]
Nice. Looks useful.

Thanks for sharing!
