### ISSUE TITLE
Could not initialize class sun.net.www.protocol.http.HttpURLConnection

### ISSUE THREAD

**Issue by gjim83** [matt-richardson/gocd-websocket-notifier#14]
Hi,

Since we updated our GoCD server to 18.6.0 we're facing this error which is not allowing for pipeline configuration to be kept in sync with the YAML files in our VCS.

After every message like 
```
2018-07-03 12:00:16,051 INFO  [150@MessageListener for PluginNotificationMessageListener] WebSocketPipelineListener:73 - notify called with request name 'stage-status' and requestBody '{"pipeline":{"name":"foo-bar",...<etc>
```

There's this message:

```
2018-07-03 12:00:16,052 WARN  [150@MessageListener for PluginNotificationMessageListener] PluginNotificationMessageListener:63 - Notification update failed for plugin: gocd.websocket.notifier
java.lang.RuntimeException: Interaction with plugin with id 'gocd.websocket.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [Could not initialize class sun.net.www.protocol.http.HttpURLConnection]
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:57)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:91)
        at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:45)
        at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:30)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Could not initialize class sun.net.www.protocol.http.HttpURLConnection
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:221)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:202)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:140)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
        ... 6 common frames omitted
Caused by: java.lang.NoClassDefFoundError: Could not initialize class sun.net.www.protocol.http.HttpURLConnection
        at sun.net.www.protocol.http.Handler.openConnection(Handler.java:62)
        at sun.net.www.protocol.http.Handler.openConnection(Handler.java:57)
        at java.net.URL.openConnection(URL.java:979)
        at com.matt_richardson.gocd.websocket_notifier.PipelineDetailsPopulator.downloadPipelineInstanceDetails(PipelineDetailsPopulator.java:36)
        at com.matt_richardson.gocd.websocket_notifier.PipelineDetailsPopulator.extendMessageToIncludePipelineDetails(PipelineDetailsPopulator.java:66)
        at com.matt_richardson.gocd.websocket_notifier.WebSocketPipelineListener.notify(WebSocketPipelineListener.java:19)
        at com.matt_richardson.gocd.websocket_notifier.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:95)
        at com.matt_richardson.gocd.websocket_notifier.GoNotificationPlugin.handle(GoNotificationPlugin.java:65)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:143)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:219)
        ... 9 common frames omitted
```

**Comment by matt-richardson** [comment]
Apologies for missing this, @gjim83. I'm hoping you managed to resolve it.

I'm intending on archiving this repo, as it's been a long time since I've used GoCD, so I'm going to close this issue.
